Improve docs remove duplicated parentheses
enzymejs/enzyme pull request #2447
Opened 2020-09-16 18:27 UTC by OtacilioN

Is there a particular reason for using duplicate parentheses in the documentation? Or it is just a minor typo?

2020-09-18 06:10 UTC, ljharb requested changes
It's quite intentional, since the "trailing comma" rule requires a trailing comma when they're omitted, but when they're included, the single jsx argument is treated as a single token, and no trailing comma is required.

2020-09-20 00:29 UTC, OtacilioN commented
I don't know if I got the reason about using duplicated parentheses, but it can be a little bit confusing, specially to beginners. 

That's no possibly to maintain the trailing coma and also remove the internal parentheses?

2020-09-20 07:00 UTC, ljharb commented
Not without violating the lint rule.

2020-09-20 12:50 UTC, OtacilioN commented
Okay got it, sorry for the pull request, to me this duplicated parentheses was very confusing.

Since it's intentional, can I close the PR? Or can we change de lint rule?

2020-09-20 21:34 UTC, ljharb commented
You'd have to change the rule inside eslint core itself first (which would be great). I think the PR can be closed, yes.

2020-09-20 21:34 UTC, closed without merging